### ISSUE TITLE
Cant turn off using of app engine email service.

### ISSUE THREAD

**Issue by yura-zh-webcodium** [GoogleCloudPlatform/wordpress-plugins#25]
I'm using WP 4.1. 
Tried to turn off "Use App Engine Email Service" option in settings, but seems this option simply doesn't work.

**Comment by sjlangley** [comment]
We just released a feature in the runtime which means we do not need the custom mail handler in the plug in. I will cut a new release of the plugin with the mail addition removed.

**Comment by welearnednothing** [comment]
Just to confirm, will this cause any issues if we have a setup that we don't to use App Engine's mail?

**Comment by welearnednothing** [comment]
Responding to my own comment - yes, this causes issues with other plugins that are trying to override WordPress's `wp_mail()` function, unfortunately. It would be great if a release was put out with the mail handler removed, but in the meantime we'll have to fork it.

**Comment by tmatsuo** [comment]
@sjlangley Are you still working on this?

**Comment by sjlangley** [comment]
No

**Comment by tmatsuo** [comment]
Sorry, but we won't add any significant feature to the App Engine plugins. We'll eventually recommend using `gcs` plugin instead.
