### ISSUE TITLE
[Future plan] Change repo name and the directory structure

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/wordpress-plugins#29]
I'm thinking to change the name of this repository to something like `wordpress-plugins` and move the current content into a sub directory `google-app-engine`, then I will add another sub directory `gcs-media` for a simpler new plugin which only hijacks the media upload feature.

I'm thinking to do it in a week or two.
Let me know if anyone has concerns.

**Comment by brandomeniconi** [comment]
Hi,
we are successfully using the plugin in more than 15 projects, its great to see this plugin backed by official support. For us there's no problem with the new directory structure. We also made some improvements to the plugin, if you can evaluate them I'll try to find time to make some PRs.

Thanks

**Comment by tmatsuo** [comment]
@brandomeniconi Thanks! I'm going to do it now.

**Comment by bshaffer** [comment]
@brandomeniconi PRs would be very much appreciated! I see you have one opened from a long time ago, we'll take a look at that one as well 😄

**Comment by brandomeniconi** [comment]
I'm little busy in this weeks, I'll try to submit the PRs ASAP.
