### ISSUE TITLE
Issue on Activating Plugin

### ISSUE THREAD

**Issue by vivekkiran** [GoogleCloudPlatform/wordpress-plugins#37]
Catchable fatal error: Argument 1 passed to GuzzleHttp\Exception\RequestException::wrapException() must implement interface Psr\Http\Message\RequestInterface, instance of GuzzleHttp\Message\Request given, called in /var/www/production/wordpress/wp-content/plugins/wp-stateless/vendor/guzzlehttp/guzzle/src/RequestFsm.php on line 104 and defined in /var/www/production/wordpress/wp-content/plugins/gcs/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 48

**Comment by tmatsuo** [comment]
Seems like there is a conflict between the dependencies of two plugins; `wp-stateless` and `gcs` (ours).

I know there's a serious problem within the WorsPress's plugin architecture and the current conventions of bundling all the dependencies.

In general, it's a serious issue, but in your case, those two plugins are very similar, so try using one at a time, not both.

**Comment by tmatsuo** [comment]
Please feel free to re-open if disabling one doesn't work

**Comment by vivekkiran** [comment]
If I remove wp-stateless and install gcs, now I am getting new Error.
Plugin could not be activated because it triggered a fatal error.
Google\Cloud\Exception\GoogleException thrown
No project ID was provided, and we were unable to detect a default project ID.

**Comment by tmatsuo** [comment]
Just for people reading this issue, the solution is posted here: https://github.com/GoogleCloudPlatform/wordpress-plugins/issues/38#issuecomment-284206719
