### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by vivekkiran** [GoogleCloudPlatform/wordpress-plugins#38]
Plugin could not be activated because it triggered a fatal error.
Google\Cloud\Exception\GoogleException thrown
No project ID was provided, and we were unable to detect a default project ID.

**Comment by tmatsuo** [comment]
@vivekkiran Sorry about the trouble.

The plugin's primary use case is on GCP. Most of our Compute platform, we can automatically detect the projectId, so it's not a problem.

If you use this plugin outside of our compute platform, you need to do several things.

1. Visit Cloud Console, go to `IAM & Admin` -> `Service accounts` and create a service account with `Storage Object Admin` permission and download the json key file.

1. Upload the json key file to the hosting server. Don't put it in a public serving area.

1. Add the following line to `wp-config.php` (replace the file path with the real one).

```
putenv('GOOGLE_APPLICATION_CREDENTIALS=/secure-place/my-service-account.json');
```

Then the plugin should be able to detect the project id from the key file.

I'll update the documentation soon.

**Comment by hyperpress** [comment]
This works for me. They'll see this in the description, and it will save misunderstandings and potential poor reviews.

**Comment by jgacuca567** [comment]
@tmatsuo were you able to update the documentation?

**Comment by nandenjin** [comment]
> 1. Visit Cloud Console, go to `IAM & Admin` -> `Service accounts` and create a service account with `Storage Object Admin` permission and download the json key file.

In my case `Storage Admin` works fine, not `Storage Object Admin`.

**Comment by n-paredes** [comment]
In my case the address was /home/<username>/etc/my-service-account.json
