### ISSUE TITLE
Update README to markdown version with additional requirements for plugin use

### ISSUE THREAD

**Issue by hyperpress** [GoogleCloudPlatform/wordpress-plugins#39]
@tmatsuo I left a note over in the WP plugin support comments a few days ago offering to update some documentation and perhaps help work on some features that would make the plugin less dependent on residing inside the GCP env. 

If you are good with that, I'll fork the repo and get to work on it. As it happens, I just got an approved signed CLA back from Google middle of last week. So that should be on file under GEMServers LLC with me as the principle, John Teague. Or, I can copy you.

Please let me know if there is anything else I need to do and I'll follow along. 

JT

**Comment by tmatsuo** [comment]
@hyperpress All sounds good :) The test won't fully work for a PR from other repo, so don't worry about it.

**Comment by tmatsuo** [comment]
@hyperpress 

Does https://github.com/GoogleCloudPlatform/wordpress-plugins/issues/38#issuecomment-284206719 work for you? If so let's just update the README.

**Comment by hyperpress** [comment]
Yes, that looks good to me. And I am done with an update of the
installation/readme I'll get that PR done by tomorrow evening latest.

**Comment by tmatsuo** [comment]
v0.1.3 released, closing
