### ISSUE TITLE
'No project ID was provided, ..." on GAE

### ISSUE THREAD

**Issue by presveva** [GoogleCloudPlatform/wordpress-plugins#44]
I'm facing the same error of #38 but I'm on a GAE project.
Any idea what I could forget?

**Comment by CaptainPatate** [comment]
I got the same issue from a fresh deployment on GAE. I think gcs-media-plugin dependency evolved somewhat and it now depends on GoogleCloudPlatform/google-cloud-php which does not seem to have project ID detection capability for the GAE platform.

A dirty patch is to specify your GCP project in gcs.php file:
```php
$config = ['projectId' => 'my-gcp-project'];
$storageClient = new \Google\Cloud\Storage\StorageClient($config);
```

**Comment by chingor13** [comment]
Is this on App Engine Standard or Flexible Environment?

**Comment by presveva** [comment]
@chingor13 standard.

**Comment by presveva** [comment]
@CaptainPatate ok, it works.

**Comment by CaptainPatate** [comment]
@presveva good :)

Yes, the appears on App Engine Standard and I think I found the underlying issue. I was not able to find the link back when I wrote my first comment, but here it is now: https://github.com/google/google-auth-library-php/issues/135

**Comment by presveva** [comment]
@CaptainPatate thank you for the workaround.

**Comment by Microserf** [comment]
Your fix worked for me @CaptainPatate! Thanks!

**Comment by csadai** [comment]
FYI For some reason, some official Google cloud librairies expect a `GCLOUD_PROJECT` envvar (and not only `GOOGLE_CLOUD_PROJECT`)

**Comment by jgacuca567** [comment]
@CaptainPatate when you deployed to your domain, where did you save your package.json file?

**Comment by CaptainPatate** [comment]
@jgacuca567 I don't remember having any file named `package.json` on my wordpress project.

**Comment by jgacuca567** [comment]
@CaptainPatate I meant your json file, when you deployed to example.com where did you save the file? Mine works locally but when I run gcloud app deploy I get the error.

**Comment by CaptainPatate** [comment]
Oh you mean the `app.yaml` file @jgacuca567? I think I put it in my project root folder. What error message did you get when you deploy?

**Comment by jgacuca567** [comment]
@CaptainPatate 
<img width="1863" alt="screen shot 2017-11-22 at 8 09 41 pm" src="https://user-images.githubusercontent.com/4000076/33155750-1d6a010c-cfc1-11e7-88b1-01166701c455.png">

**Comment by ran-dall** [comment]
@JamesVanWaza I don't know if you still are having the issue. But I was having this issue when my .json key was saved to my project root. I moved it to /etc and it worked. Check my issue #61 for some details but I'm pretty sure if you move the key and you update your gcs.php, you'll be fine.

**Comment by JamesVanWaza** [comment]
@ran-dall do you mind, creating a video, showing the fix? How can I assist?

**Comment by ran-dall** [comment]
@JamesVanWaza I'd be happy to create a video or walkthrough of some kind for you. I don't have time right now cause I'm about to leave for the holiday but maybe during, I'll have some extra time. I created an issue (https://github.com/GoogleCloudPlatform/wordpress-plugins/issues/61) before with some details, have you checked that?

**Comment by JamesVanWaza** [comment]
@ran-dall I am still having problems, with it. Maybe you can create a video showing the solution.

**Comment by ran-dall** [comment]
@JamesVanWaza I apologize for not seeing your message. 😁. I'll look into it over the next couple of days and let you know what I come up with...

**Comment by JamesVanWaza** [comment]
@ran-dall its been 5 months. Any help?

**Comment by ToddKopriva** [comment]
The Issues section of this GitHub repository is not the best place to get such questions answered quickly. I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
