### ISSUE TITLE
The bucket does not exist, or is not writable

### ISSUE THREAD

**Issue by rieznik** [GoogleCloudPlatform/wordpress-plugins#48]
I have installed the plugin as per Installation guide but used this fix for "No project ID was provided" https://github.com/GoogleCloudPlatform/wordpress-plugins/issues/44#issuecomment-300535176 

Now I am getting an error saying “The bucket does not exist, or is not writable” while setting the bucket name.

**Comment by DNepovim** [comment]
@rieznik Is this solved? I have the same issue.

**Comment by rieznik** [comment]
@DNepovim I do not know, I just started using another plugin :(

**Comment by bshaffer** [comment]
@DNepovim where are you running the plugin? If you're running on Google Compute Engine (GCE) you will need to update the **Cloud API access scopes** on your VM instance to be "Read/Write" for Google Cloud Storage in order for the plugin to work.
