### ISSUE TITLE
Is it possible to use the plugin with permissions?

### ISSUE THREAD

**Issue by Steffi3rd** [GoogleCloudPlatform/wordpress-plugins#63]
Hi, I tried this plugin but I doesn't work as I excepted.

In my case, I would like each Wordpress user can upload their photos but others Wordpress Users can see OR access to these files. Even Wordpress administrators cannot access to the files. (That's why I don't want them is the "Wordpress Media Library")

Is there a way to do that with this plugin please?

**Comment by bshaffer** [comment]
Hello! Unfortunately this plugin does not handle that use case. You will want to build out custom permissions to handle this use case, e.g. create a folder with each user's username, and verify the logged-in user's identity before modifying objects in that bucket.
