### ISSUE TITLE
PHP Fatal error:  Uncaught Google\Cloud\Core\Exception\ServiceException: cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection

### ISSUE THREAD

**Issue by kientv** [GoogleCloudPlatform/wordpress-plugins#74]
I saw this bug when using gcs plugin with WordPress 5.7.2 (https://wordpress.org/plugins/gcs/)
I'm using php:8.0-fpm-alpine 

`
Uncaught Google\Cloud\Core\Exception\ServiceException: cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to oauth2.googleapis.com:443  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/wp-content/plugins/gcs/vendor/google/cloud-core/src/RequestWrapper.php:362
`

**Comment by logicalphase** [comment]
Check with your hosting provider, or diagnose if your running the latest
(or at least a near latest) version of cURL on the web server. That often
is the cause of 35 errors.

**Comment by kientv** [comment]
I changed my DNS to 8.8.8.8 and it work fine now.

Thank you
